# Generated by Django 2.2.28 on 2023-07-06 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ssf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnvnfn', models.BigIntegerField()),
                ('errr', models.BigIntegerField()),
                ('rel_user_1_1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ssf_rel_user_1_1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
