# Generated by Django 2.2.28 on 2023-07-06 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_auto_20230706_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='fdhd',
            name='cvcvcb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fdhd_cvcvcb', to=settings.AUTH_USER_MODEL),
        ),
    ]
